# Generated by Django 4.2.1 on 2023-10-16 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='odered_date',
            new_name='ordered_date',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_order_status',
            new_name='razorpay_payment_status',
        ),
    ]
