# Generated by Django 4.2.1 on 2023-10-18 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_payment_razorpay_payment_id_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='prodapp',
            new_name='product',
        ),
    ]
